<?xml version="1.0"?>
<!DOCTYPE coverage SYSTEM "http://cobertura.sourceforge.net/xml/coverage-04.dtd" [
    <!ELEMENT coverage (sources?, packages)>
    <!ATTLIST coverage line-rate CDATA #REQUIRED>
    <!ATTLIST coverage branch-rate CDATA #REQUIRED>
    <!ATTLIST coverage lines-covered CDATA #REQUIRED>
    <!ATTLIST coverage lines-valid CDATA #REQUIRED>
    <!ATTLIST coverage branches-covered CDATA #REQUIRED>
    <!ATTLIST coverage branches-valid CDATA #REQUIRED>
    <!ATTLIST coverage complexity CDATA #REQUIRED>
    <!ATTLIST coverage version CDATA #REQUIRED>
    <!ATTLIST coverage timestamp CDATA #REQUIRED>
    <!ELEMENT sources (source)*>
    <!ELEMENT source (#PCDATA)>
    <!ELEMENT packages (package)*>
    <!ELEMENT package (classes)>
    <!ATTLIST package name CDATA #REQUIRED>
    <!ATTLIST package line-rate CDATA #REQUIRED>
    <!ATTLIST package branch-rate CDATA #REQUIRED>
    <!ATTLIST package complexity CDATA #REQUIRED>
    <!ELEMENT classes (class)*>
    <!ELEMENT class (methods, lines)>
    <!ATTLIST class name CDATA #REQUIRED>
    <!ATTLIST class filename CDATA #REQUIRED>
    <!ATTLIST class line-rate CDATA #REQUIRED>
    <!ATTLIST class branch-rate CDATA #REQUIRED>
    <!ATTLIST class complexity CDATA #REQUIRED>
    <!ELEMENT methods (method)*>
    <!ELEMENT method (lines)>
    <!ATTLIST method name CDATA #REQUIRED>
    <!ATTLIST method signature CDATA #REQUIRED>
    <!ATTLIST method line-rate CDATA #REQUIRED>
    <!ATTLIST method branch-rate CDATA #REQUIRED>
    <!ATTLIST method complexity CDATA #REQUIRED>
    <!ELEMENT lines (line)*>
    <!ELEMENT line (conditions)*>
    <!ATTLIST line number CDATA #REQUIRED>
    <!ATTLIST line hits CDATA #REQUIRED>
    <!ATTLIST line branch CDATA "false">
    <!ATTLIST line condition-coverage CDATA "100%">
    <!ELEMENT conditions (condition)*>
    <!ELEMENT condition EMPTY>
    <!ATTLIST condition number CDATA #REQUIRED>
    <!ATTLIST condition type CDATA #REQUIRED>
    <!ATTLIST condition coverage CDATA #REQUIRED>
]>

<coverage line-rate="0.5192307692307693" branch-rate="1.0" lines-covered="27" lines-valid="52" timestamp="1643782824.853012" version="diff_coverage 0.1" complexity="0.0" branches-valid="1.0" branches-covered="1.0">
    <sources>
        <source>/Users/cloymonis/VServWorkspace/Git_Source/ng_dump/CI_CD/NGCorePocLib</source>
    </sources>
    <packages>
        <package name="NGCorePocLib.Classes.Core" line-rate="1.0" branch-rate="1.0" complexity="0.0">
            <class name="NGCorePocLib.Classes.Core.NGCorePocMain" filename="NGCorePocLib/Classes/Core/NGCorePocMain.swift" line-rate="1.0" branch-rate="1.0" complexity="0.0">
                <lines>
                    <line number="14" branch="false" hits="2"/>
                    <line number="15" branch="false" hits="2"/>
                    <line number="16" branch="false" hits="2"/>
                </lines>
            </class>
        </package>
        <package name="Example.NGCorePocLib" line-rate="0.6190476190476191" branch-rate="1.0" complexity="0.0">
            <class name="Example.NGCorePocLib.ViewController" filename="Example/NGCorePocLib/ViewController.swift" line-rate="0.6190476190476191" branch-rate="1.0" complexity="0.0">
                <lines>
                    <line number="20" branch="false" hits="1"/>
                    <line number="21" branch="false" hits="1"/>
                    <line number="22" branch="false" hits="1"/>
                    <line number="23" branch="false" hits="1"/>
                    <line number="24" branch="false" hits="1"/>
                    <line number="25" branch="false" hits="1"/>
                    <line number="26" branch="false" hits="1"/>
                    <line number="27" branch="false" hits="1"/>
                    <line number="28" branch="false" hits="1"/>
                    <line number="29" branch="false" hits="1"/>
                    <line number="30" branch="false" hits="1"/>
                    <line number="31" branch="false" hits="1"/>
                    <line number="32" branch="false" hits="1"/>
                    <line number="33" branch="false" hits="0"/>
                    <line number="34" branch="false" hits="0"/>
                    <line number="35" branch="false" hits="0"/>
                    <line number="36" branch="false" hits="0"/>
                    <line number="38" branch="false" hits="0"/>
                    <line number="39" branch="false" hits="0"/>
                    <line number="40" branch="false" hits="0"/>
                    <line number="41" branch="false" hits="0"/>
                </lines>
            </class>
            <class name="Example.NGCorePocLib.AppDelegate" filename="Example/NGCorePocLib/AppDelegate.swift" line-rate="0.39285714285714285" branch-rate="1.0" complexity="0.0">
                <lines>
                    <line number="20" branch="false" hits="1"/>
                    <line number="21" branch="false" hits="1"/>
                    <line number="22" branch="false" hits="1"/>
                    <line number="23" branch="false" hits="1"/>
                    <line number="24" branch="false" hits="1"/>
                    <line number="25" branch="false" hits="1"/>
                    <line number="26" branch="false" hits="1"/>
                    <line number="27" branch="false" hits="1"/>
                    <line number="29" branch="false" hits="0"/>
                    <line number="30" branch="false" hits="0"/>
                    <line number="31" branch="false" hits="0"/>
                    <line number="32" branch="false" hits="0"/>
                    <line number="33" branch="false" hits="0"/>
                    <line number="34" branch="false" hits="0"/>
                    <line number="36" branch="false" hits="0"/>
                    <line number="37" branch="false" hits="0"/>
                    <line number="38" branch="false" hits="0"/>
                    <line number="39" branch="false" hits="0"/>
                    <line number="40" branch="false" hits="0"/>
                    <line number="42" branch="false" hits="0"/>
                    <line number="43" branch="false" hits="0"/>
                    <line number="44" branch="false" hits="0"/>
                    <line number="46" branch="false" hits="1"/>
                    <line number="47" branch="false" hits="1"/>
                    <line number="48" branch="false" hits="1"/>
                    <line number="50" branch="false" hits="0"/>
                    <line number="51" branch="false" hits="0"/>
                    <line number="52" branch="false" hits="0"/>
                </lines>
            </class>
        </package>
    </packages>
</coverage>
